#!/usr/bin/with-contenv bash
# shellcheck shell=bash

[ -z "$PUID" ] && PUID=911
[ -z "$PGID" ] && PGID=911

# create our folders
mkdir -p \
    /config/settings \
    /downloads

# default config file
cp -n \
    /defaults/pyload.cfg \
    /config/settings/pyload.cfg

# permissions
lsiown -R $PUID:$PGID \
    /config
lsiown $PUID:$PGID \
    /downloads
